config/routes.rb
Rails.application.routes.draw do
  root  'lines#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create]

  get '/bookmarks', to: 'stations#bookmark'
  get '/:code', to: 'stations#index'

  resources :stations do
    resource :bookmarks, only: [:create, :destroy], param: :station_code
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :station, foreign_key: :station_code

  validates :user_id, uniqueness: { scope: :station_code }
end

app/models/company.rb
class Company < ApplicationRecord
  self.primary_key = :company_code

  has_many :lines, dependent: :destroy
  has_many :stations, dependent: :destroy

  validates :company_code, presence: true, uniqueness: true
  validates :name, presence: true
end

app/models/line.rb
class Line < ApplicationRecord
  self.primary_key = :line_code

  belongs_to :company, foreign_key: :company_code
  has_many :lines_stations, foreign_key: :line_code
  has_many :stations, through: :lines_stations

  validates :line_code, presence: true, uniqueness: true
  validates :name, presence: true
end

app/models/lines_station.rb
class LinesStation < ApplicationRecord
  belongs_to :line, foreign_key: :line_code
  belongs_to :station, foreign_key: :station_code

  validates :line_code, uniqueness: { scope: :station_code }
end

app/models/station.rb
class Station < ApplicationRecord
  self.primary_key = :station_code

  belongs_to :company, foreign_key: :company_code
  has_many :lines_stations, foreign_key: :station_code
  has_many :lines, through: :lines_stations
  has_many :bookmarks, dependent: :destroy, foreign_key: :station_code
  has_many :users, through: :bookmarks

  validates :station_code, presence: true, uniqueness: true
  validates :name, presence: true

  def to_param
    station_code
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :bookmarks, dependent: :destroy
  has_many :stations, through: :bookmarks

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  enum role: { general: 0, guest: 1 }

  def already_bookmark?(line_station)
    self.bookmarks.exists?(station_code: line_station.station_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = current_user.bookmarks.create(station_code: params[:station_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @station = Station.find_by(station_code: params[:station_code])
    @bookmark = current_user.bookmarks.find_by(station_code: params[:station_id])
    @bookmark.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    redirect_to "/11302"
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @line = Line.all
    @params_line = Line.find(params[:code])
    @line_station = Station.joins(:lines_stations).where(lines_stations: { line_code: params[:code] }).order(order: :asc)
  end

  def bookmark
    @line = Line.all
    @bookmark_station = Station.joins(:bookmarks).where(bookmarks: { user_id: current_user.id }).order(id: :asc)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトしました'
  end

  def guest_login
    rondom_value = SecureRandom.alphanumeric(10) + Time.zone.now.to_i.to_s
    @guest_user = User.create(
      email: rondom_value + '@example.com',
      password: 'password',
      password_confirmation: 'password',
      role: :guest
    )
    auto_login(@guest_user)
    redirect_back_or_to root_path, success: 'お試しで使用中です'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      logout
      redirect_to root_path
    else
      render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapitalIntensityRouteMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/logged_in_header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lines/show.html.erb
<div class="row">
  <%= render 'shared/sidebar' %>

  <div class="col-md-10">
    <div class="mx-5">
      <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1><%= @params_line.name %></h1>
        <p><%= @params_line.name %>の駅に位置する地点が、30年以内に震度６弱・震度６強以上の揺れに見舞われる確率を示しています。</p>
      </div>

      <div class="text-center">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">駅名</th>
              <th scope="col">震度６弱 発生確率</th>
              <th scope="col">震度６強 発生確率</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @line_station.each do |ls| %>
              <tr>
                <td><%= ls.name %></td>
                <td>
                  <div class="progress-bar <%= ls.lower_six >= 0.508 ? "bg-danger" : "bg-warning" %>" style="width: <%= ls.lower_six * 100 %>%;">
                    <%= (ls.lower_six * 100).round(0) %>
                  </div>
                </td>
                <td>
                  <div class="progress-bar <%= ls.upper_six >= 0.098 ? "bg-danger" : "bg-warning" %>" style="width: <%= ls.upper_six * 100 %>%;">
                    <%= (ls.upper_six * 100).round(0) %>
                  </div>
                </td>
                <td><%= link_to "目的地まで", "#" %></td>
                <td><%= link_to "☆", "#" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #13BF00;">
    <div class="container-fluid">
      <%= link_to '首都圏震度路線図', root_path, class: 'navbar-brand' %>
      <div class="navbar-collapse justify-content-end">
        <ul class="navbar-nav nav ms-auto">
          <li class="nav-item  mx-2">
            <%= button_to 'お試しで使う', guest_login_path, class: 'btn btn-light' %>
          </li>
          <li class="nav-item  mx-2">
            <%= button_to '新規登録', new_user_path, method: :get, class: 'btn btn-light' %>
          </li>
          <li class="nav-item  mx-2">
            <%= button_to 'ログイン', login_path, method: :get, class: 'btn btn-light' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_logged_in_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #13BF00;">
    <div class="container-fluid">
      <%= link_to '首都圏震度路線図', root_path, class: 'navbar-brand' %>
      <div class="navbar-collapse justify-content-end">
        <ul class="navbar-nav nav">
          <li class="nav-item  mx-2">
            <%= button_to '目的地設定', "#", method: :get, class: 'btn btn-light' %>
          <li class="nav-item  mx-2">
            <%= button_to 'ブックマーク一覧', bookmarks_path, method: :get, class: 'btn btn-light' %>
          </li>
          <li class="nav-item  mx-2">
            <%= button_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-light' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_sidebar.html.erb
<div class="col-md-2">
  <div class="d-flex flex-column px-3 py-5 bg-light h-100">
    <% @line.each do |l| %>
      <div class="nav-link">
        <%= link_to "#{l.name}", "/#{l.line_code}" %>
      </div>
    <% end %>
  </div>
</div>

app/views/stations/bookmark.html.erb
<div class="row">
  <%= render 'shared/sidebar' %>

  <div class="col-md-10">
    <div class="mx-5">
      <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1>ブックマーク一覧</h1>
      </div>

      <div class="text-center">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">駅名</th>
              <th scope="col">震度６弱 発生確率</th>
              <th scope="col">震度６強 発生確率</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @bookmark_station.each do |bs| %>
              <tr>
                <td><%= bs.name %></td>
                <td>
                  <div class="progress-bar <%= bs.lower_six >= 0.508 ? "bg-danger" : "bg-warning" %>" style="width: <%= bs.lower_six * 100 %>%;">
                    <%= (bs.lower_six * 100).round(0) %>
                  </div>
                </td>
                <td>
                  <div class="progress-bar <%= bs.upper_six >= 0.098 ? "bg-danger" : "bg-warning" %>" style="width: <%= bs.upper_six * 100 %>%;">
                    <%= (bs.upper_six * 100).round(0) %>
                  </div>
                </td>
                <td><%= link_to "目的地まで", "#" %></td>
                <% if current_user %>
                  <% if current_user.already_bookmark?(bs) %>
                    <td>
                      <%= link_to station_bookmarks_path(bs.station_code), method: :delete do %>
                        <%= icon 'fas', 'star' %>
                      <% end %>
                    </td>
                  <% else %>
                    <td>
                      <%= link_to station_bookmarks_path(bs.station_code), method: :post do %>
                        <%= icon 'far', 'star' %>
                      <% end %>
                    </td>
                  <% end %>
                <% else %>
                  <td><%= link_to "☆", new_user_path %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

app/views/stations/index.html.erb
<div class="row">
  <%= render 'shared/sidebar' %>

  <div class="col-md-10">
    <div class="mx-5">
      <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1><%= @params_line.name %></h1>
        <p><%= @params_line.name %>の駅に位置する地点が、30年以内に震度６弱・震度６強以上の揺れに見舞われる確率を示しています。</p>
      </div>

      <div class="text-center">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">駅名</th>
              <th scope="col">震度６弱 発生確率</th>
              <th scope="col">震度６強 発生確率</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @line_station.each do |ls| %>
              <tr>
                <td><%= ls.name %></td>
                <td>
                  <div class="progress-bar <%= ls.lower_six >= 0.508 ? "bg-danger" : "bg-warning" %>" style="width: <%= ls.lower_six * 100 %>%;">
                    <%= (ls.lower_six * 100).round(0) %>
                  </div>
                </td>
                <td>
                  <div class="progress-bar <%= ls.upper_six >= 0.098 ? "bg-danger" : "bg-warning" %>" style="width: <%= ls.upper_six * 100 %>%;">
                    <%= (ls.upper_six * 100).round(0) %>
                  </div>
                </td>
                <td><%= link_to "目的地まで", "#" %></td>
                <% if current_user %>
                  <% if current_user.already_bookmark?(ls) %>
                    <td>
                      <%= link_to station_bookmarks_path(ls.station_code), method: :delete do %>
                        <%= icon 'fas', 'star' %>
                      <% end %>
                    </td>
                  <% else %>
                    <td>
                      <%= link_to station_bookmarks_path(ls.station_code), method: :post do %>
                        <%= icon 'far', 'star' %>
                      <% end %>
                    </td>
                  <% end %>
                <% else %>
                  <td>
                    <%= link_to new_user_path do %>
                      <%= icon 'far', 'star' %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="wrapper">
    <h1 class="h3 my-4 text-center">ユーザーログイン</h1>

    <%= form_with url: login_path, local: true do |f| %>
      <%= f.label 'メールアドレス' %><br/>
      <%= f.text_field :email, class: 'form-control mb-3' %>
      <%= f.label 'パスワード' %><br/>
      <%= f.password_field :password, class: 'form-control mb-3' %>
      <div class="text-center">
        <%= f.submit 'ログインする', class: 'btn btn-primary mb-3' %>
      </div>
    <% end %> 
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="wrapper">
    <h1 class="h3 my-4 text-center">ユーザー登録</h1>

    <%= form_with model: @user, local: true do |f| %>
      <% if @user.errors.present? %>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="mb-3">
        <%= f.label 'メールアドレス' %><br/>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label 'パスワード' %><br/>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label 'パスワード（確認）' %><br/>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <br/>
      <div class="text-center">
        <%= f.submit 'ユーザー登録する', class: 'btn btn-primary text-center' %>
      </div>
    <% end %>
  </div>
</div>